import type { Metadata } from 'next';
import { ReactNode } from 'react';
import localFont from 'next/font/local';

import './globals.css';
import 'maplibre-gl/dist/maplibre-gl.css';

const globalFont = localFont({
  src: '../assets/fonts/Pretendard.woff2',
  display: 'swap',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko" className={globalFont.variable}>
      <body>
        <div className="w-full h-full flex flex-col">
          <div className="w-full h-16 bg-red-500" />
          {children}
        </div>
      </body>
    </html>
  );
}
